### ISSUE TITLE
Don't work 😡

### ISSUE THREAD

**Issue by ALEZ-DEV** [MATMAF/nextjs-dashboard#1]
😡
![image](https://github.com/MATMAF/nextjs-dashboard/assets/38623465/892243a2-a95c-4c42-a006-22d805b178ce)

**Comment by MATMAF** [comment]
C'est la faute a pas de chance.
Je fais le tuto donc normal.

**Comment by ALEZ-DEV** [comment]
Flutter >> React

**Comment by MATMAF** [comment]
C'est pour faire mon app atlassian connect

**Comment by ALEZ-DEV** [comment]
J'ai remarqué, bonne chance

**Comment by MATMAF** [comment]
Et pour la maintenance c'est plus simple et il me faut des trucs sur javascript
